// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: user.proto

package com.javatab.kafka.model.proto;

public final class UserProtos {
  private UserProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:com.javatab.kafka.model.proto.User)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    java.lang.String getName();
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    java.lang.String getId();
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    com.google.protobuf.ByteString
        getIdBytes();

    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    java.lang.String getEmail();
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    com.google.protobuf.ByteString
        getEmailBytes();

    /**
     * <code>.google.protobuf.Timestamp created_on = 4;</code>
     * @return Whether the createdOn field is set.
     */
    boolean hasCreatedOn();
    /**
     * <code>.google.protobuf.Timestamp created_on = 4;</code>
     * @return The createdOn.
     */
    com.google.protobuf.Timestamp getCreatedOn();
    /**
     * <code>.google.protobuf.Timestamp created_on = 4;</code>
     */
    com.google.protobuf.TimestampOrBuilder getCreatedOnOrBuilder();

    /**
     * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
     * @return Whether the address field is set.
     */
    boolean hasAddress();
    /**
     * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
     * @return The address.
     */
    com.javatab.kafka.model.proto.UserProtos.User.Address getAddress();
    /**
     * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
     */
    com.javatab.kafka.model.proto.UserProtos.User.AddressOrBuilder getAddressOrBuilder();
  }
  /**
   * Protobuf type {@code com.javatab.kafka.model.proto.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:com.javatab.kafka.model.proto.User)
      UserOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use User.newBuilder() to construct.
    private User(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private User() {
      name_ = "";
      id_ = "";
      email_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new User();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private User(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              name_ = s;
              break;
            }
            case 18: {
              java.lang.String s = input.readStringRequireUtf8();

              id_ = s;
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              email_ = s;
              break;
            }
            case 34: {
              com.google.protobuf.Timestamp.Builder subBuilder = null;
              if (createdOn_ != null) {
                subBuilder = createdOn_.toBuilder();
              }
              createdOn_ = input.readMessage(com.google.protobuf.Timestamp.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(createdOn_);
                createdOn_ = subBuilder.buildPartial();
              }

              break;
            }
            case 42: {
              com.javatab.kafka.model.proto.UserProtos.User.Address.Builder subBuilder = null;
              if (address_ != null) {
                subBuilder = address_.toBuilder();
              }
              address_ = input.readMessage(com.javatab.kafka.model.proto.UserProtos.User.Address.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(address_);
                address_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.javatab.kafka.model.proto.UserProtos.User.class, com.javatab.kafka.model.proto.UserProtos.User.Builder.class);
    }

    public interface AddressOrBuilder extends
        // @@protoc_insertion_point(interface_extends:com.javatab.kafka.model.proto.User.Address)
        com.google.protobuf.MessageOrBuilder {

      /**
       * <code>string streetName = 1;</code>
       * @return The streetName.
       */
      java.lang.String getStreetName();
      /**
       * <code>string streetName = 1;</code>
       * @return The bytes for streetName.
       */
      com.google.protobuf.ByteString
          getStreetNameBytes();

      /**
       * <code>string city = 2;</code>
       * @return The city.
       */
      java.lang.String getCity();
      /**
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      com.google.protobuf.ByteString
          getCityBytes();

      /**
       * <code>string state = 3;</code>
       * @return The state.
       */
      java.lang.String getState();
      /**
       * <code>string state = 3;</code>
       * @return The bytes for state.
       */
      com.google.protobuf.ByteString
          getStateBytes();

      /**
       * <code>string zipCode = 4;</code>
       * @return The zipCode.
       */
      java.lang.String getZipCode();
      /**
       * <code>string zipCode = 4;</code>
       * @return The bytes for zipCode.
       */
      com.google.protobuf.ByteString
          getZipCodeBytes();
    }
    /**
     * Protobuf type {@code com.javatab.kafka.model.proto.User.Address}
     */
    public  static final class Address extends
        com.google.protobuf.GeneratedMessageV3 implements
        // @@protoc_insertion_point(message_implements:com.javatab.kafka.model.proto.User.Address)
        AddressOrBuilder {
    private static final long serialVersionUID = 0L;
      // Use Address.newBuilder() to construct.
      private Address(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
        super(builder);
      }
      private Address() {
        streetName_ = "";
        city_ = "";
        state_ = "";
        zipCode_ = "";
      }

      @java.lang.Override
      @SuppressWarnings({"unused"})
      protected java.lang.Object newInstance(
          UnusedPrivateParameter unused) {
        return new Address();
      }

      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
      getUnknownFields() {
        return this.unknownFields;
      }
      private Address(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        this();
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 10: {
                java.lang.String s = input.readStringRequireUtf8();

                streetName_ = s;
                break;
              }
              case 18: {
                java.lang.String s = input.readStringRequireUtf8();

                city_ = s;
                break;
              }
              case 26: {
                java.lang.String s = input.readStringRequireUtf8();

                state_ = s;
                break;
              }
              case 34: {
                java.lang.String s = input.readStringRequireUtf8();

                zipCode_ = s;
                break;
              }
              default: {
                if (!parseUnknownField(
                    input, unknownFields, extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_Address_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_Address_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.javatab.kafka.model.proto.UserProtos.User.Address.class, com.javatab.kafka.model.proto.UserProtos.User.Address.Builder.class);
      }

      public static final int STREETNAME_FIELD_NUMBER = 1;
      private volatile java.lang.Object streetName_;
      /**
       * <code>string streetName = 1;</code>
       * @return The streetName.
       */
      public java.lang.String getStreetName() {
        java.lang.Object ref = streetName_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          streetName_ = s;
          return s;
        }
      }
      /**
       * <code>string streetName = 1;</code>
       * @return The bytes for streetName.
       */
      public com.google.protobuf.ByteString
          getStreetNameBytes() {
        java.lang.Object ref = streetName_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          streetName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int CITY_FIELD_NUMBER = 2;
      private volatile java.lang.Object city_;
      /**
       * <code>string city = 2;</code>
       * @return The city.
       */
      public java.lang.String getCity() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          city_ = s;
          return s;
        }
      }
      /**
       * <code>string city = 2;</code>
       * @return The bytes for city.
       */
      public com.google.protobuf.ByteString
          getCityBytes() {
        java.lang.Object ref = city_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          city_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int STATE_FIELD_NUMBER = 3;
      private volatile java.lang.Object state_;
      /**
       * <code>string state = 3;</code>
       * @return The state.
       */
      public java.lang.String getState() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          state_ = s;
          return s;
        }
      }
      /**
       * <code>string state = 3;</code>
       * @return The bytes for state.
       */
      public com.google.protobuf.ByteString
          getStateBytes() {
        java.lang.Object ref = state_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          state_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      public static final int ZIPCODE_FIELD_NUMBER = 4;
      private volatile java.lang.Object zipCode_;
      /**
       * <code>string zipCode = 4;</code>
       * @return The zipCode.
       */
      public java.lang.String getZipCode() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          zipCode_ = s;
          return s;
        }
      }
      /**
       * <code>string zipCode = 4;</code>
       * @return The bytes for zipCode.
       */
      public com.google.protobuf.ByteString
          getZipCodeBytes() {
        java.lang.Object ref = zipCode_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          zipCode_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      private byte memoizedIsInitialized = -1;
      @java.lang.Override
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized == 1) return true;
        if (isInitialized == 0) return false;

        memoizedIsInitialized = 1;
        return true;
      }

      @java.lang.Override
      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        if (!getStreetNameBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 1, streetName_);
        }
        if (!getCityBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 2, city_);
        }
        if (!getStateBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 3, state_);
        }
        if (!getZipCodeBytes().isEmpty()) {
          com.google.protobuf.GeneratedMessageV3.writeString(output, 4, zipCode_);
        }
        unknownFields.writeTo(output);
      }

      @java.lang.Override
      public int getSerializedSize() {
        int size = memoizedSize;
        if (size != -1) return size;

        size = 0;
        if (!getStreetNameBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, streetName_);
        }
        if (!getCityBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, city_);
        }
        if (!getStateBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, state_);
        }
        if (!getZipCodeBytes().isEmpty()) {
          size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, zipCode_);
        }
        size += unknownFields.getSerializedSize();
        memoizedSize = size;
        return size;
      }

      @java.lang.Override
      public boolean equals(final java.lang.Object obj) {
        if (obj == this) {
         return true;
        }
        if (!(obj instanceof com.javatab.kafka.model.proto.UserProtos.User.Address)) {
          return super.equals(obj);
        }
        com.javatab.kafka.model.proto.UserProtos.User.Address other = (com.javatab.kafka.model.proto.UserProtos.User.Address) obj;

        if (!getStreetName()
            .equals(other.getStreetName())) return false;
        if (!getCity()
            .equals(other.getCity())) return false;
        if (!getState()
            .equals(other.getState())) return false;
        if (!getZipCode()
            .equals(other.getZipCode())) return false;
        if (!unknownFields.equals(other.unknownFields)) return false;
        return true;
      }

      @java.lang.Override
      public int hashCode() {
        if (memoizedHashCode != 0) {
          return memoizedHashCode;
        }
        int hash = 41;
        hash = (19 * hash) + getDescriptor().hashCode();
        hash = (37 * hash) + STREETNAME_FIELD_NUMBER;
        hash = (53 * hash) + getStreetName().hashCode();
        hash = (37 * hash) + CITY_FIELD_NUMBER;
        hash = (53 * hash) + getCity().hashCode();
        hash = (37 * hash) + STATE_FIELD_NUMBER;
        hash = (53 * hash) + getState().hashCode();
        hash = (37 * hash) + ZIPCODE_FIELD_NUMBER;
        hash = (53 * hash) + getZipCode().hashCode();
        hash = (29 * hash) + unknownFields.hashCode();
        memoizedHashCode = hash;
        return hash;
      }

      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          java.nio.ByteBuffer data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          java.nio.ByteBuffer data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input);
      }
      public static com.javatab.kafka.model.proto.UserProtos.User.Address parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return com.google.protobuf.GeneratedMessageV3
            .parseWithIOException(PARSER, input, extensionRegistry);
      }

      @java.lang.Override
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder() {
        return DEFAULT_INSTANCE.toBuilder();
      }
      public static Builder newBuilder(com.javatab.kafka.model.proto.UserProtos.User.Address prototype) {
        return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
      }
      @java.lang.Override
      public Builder toBuilder() {
        return this == DEFAULT_INSTANCE
            ? new Builder() : new Builder().mergeFrom(this);
      }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code com.javatab.kafka.model.proto.User.Address}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
          // @@protoc_insertion_point(builder_implements:com.javatab.kafka.model.proto.User.Address)
          com.javatab.kafka.model.proto.UserProtos.User.AddressOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_Address_descriptor;
        }

        @java.lang.Override
        protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_Address_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  com.javatab.kafka.model.proto.UserProtos.User.Address.class, com.javatab.kafka.model.proto.UserProtos.User.Address.Builder.class);
        }

        // Construct using com.javatab.kafka.model.proto.UserProtos.User.Address.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessageV3
                  .alwaysUseFieldBuilders) {
          }
        }
        @java.lang.Override
        public Builder clear() {
          super.clear();
          streetName_ = "";

          city_ = "";

          state_ = "";

          zipCode_ = "";

          return this;
        }

        @java.lang.Override
        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_Address_descriptor;
        }

        @java.lang.Override
        public com.javatab.kafka.model.proto.UserProtos.User.Address getDefaultInstanceForType() {
          return com.javatab.kafka.model.proto.UserProtos.User.Address.getDefaultInstance();
        }

        @java.lang.Override
        public com.javatab.kafka.model.proto.UserProtos.User.Address build() {
          com.javatab.kafka.model.proto.UserProtos.User.Address result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        @java.lang.Override
        public com.javatab.kafka.model.proto.UserProtos.User.Address buildPartial() {
          com.javatab.kafka.model.proto.UserProtos.User.Address result = new com.javatab.kafka.model.proto.UserProtos.User.Address(this);
          result.streetName_ = streetName_;
          result.city_ = city_;
          result.state_ = state_;
          result.zipCode_ = zipCode_;
          onBuilt();
          return result;
        }

        @java.lang.Override
        public Builder clone() {
          return super.clone();
        }
        @java.lang.Override
        public Builder setField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.setField(field, value);
        }
        @java.lang.Override
        public Builder clearField(
            com.google.protobuf.Descriptors.FieldDescriptor field) {
          return super.clearField(field);
        }
        @java.lang.Override
        public Builder clearOneof(
            com.google.protobuf.Descriptors.OneofDescriptor oneof) {
          return super.clearOneof(oneof);
        }
        @java.lang.Override
        public Builder setRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            int index, java.lang.Object value) {
          return super.setRepeatedField(field, index, value);
        }
        @java.lang.Override
        public Builder addRepeatedField(
            com.google.protobuf.Descriptors.FieldDescriptor field,
            java.lang.Object value) {
          return super.addRepeatedField(field, value);
        }
        @java.lang.Override
        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof com.javatab.kafka.model.proto.UserProtos.User.Address) {
            return mergeFrom((com.javatab.kafka.model.proto.UserProtos.User.Address)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(com.javatab.kafka.model.proto.UserProtos.User.Address other) {
          if (other == com.javatab.kafka.model.proto.UserProtos.User.Address.getDefaultInstance()) return this;
          if (!other.getStreetName().isEmpty()) {
            streetName_ = other.streetName_;
            onChanged();
          }
          if (!other.getCity().isEmpty()) {
            city_ = other.city_;
            onChanged();
          }
          if (!other.getState().isEmpty()) {
            state_ = other.state_;
            onChanged();
          }
          if (!other.getZipCode().isEmpty()) {
            zipCode_ = other.zipCode_;
            onChanged();
          }
          this.mergeUnknownFields(other.unknownFields);
          onChanged();
          return this;
        }

        @java.lang.Override
        public final boolean isInitialized() {
          return true;
        }

        @java.lang.Override
        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          com.javatab.kafka.model.proto.UserProtos.User.Address parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (com.javatab.kafka.model.proto.UserProtos.User.Address) e.getUnfinishedMessage();
            throw e.unwrapIOException();
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }

        private java.lang.Object streetName_ = "";
        /**
         * <code>string streetName = 1;</code>
         * @return The streetName.
         */
        public java.lang.String getStreetName() {
          java.lang.Object ref = streetName_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            streetName_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string streetName = 1;</code>
         * @return The bytes for streetName.
         */
        public com.google.protobuf.ByteString
            getStreetNameBytes() {
          java.lang.Object ref = streetName_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            streetName_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string streetName = 1;</code>
         * @param value The streetName to set.
         * @return This builder for chaining.
         */
        public Builder setStreetName(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          streetName_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string streetName = 1;</code>
         * @return This builder for chaining.
         */
        public Builder clearStreetName() {
          
          streetName_ = getDefaultInstance().getStreetName();
          onChanged();
          return this;
        }
        /**
         * <code>string streetName = 1;</code>
         * @param value The bytes for streetName to set.
         * @return This builder for chaining.
         */
        public Builder setStreetNameBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          streetName_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object city_ = "";
        /**
         * <code>string city = 2;</code>
         * @return The city.
         */
        public java.lang.String getCity() {
          java.lang.Object ref = city_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            city_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string city = 2;</code>
         * @return The bytes for city.
         */
        public com.google.protobuf.ByteString
            getCityBytes() {
          java.lang.Object ref = city_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            city_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string city = 2;</code>
         * @param value The city to set.
         * @return This builder for chaining.
         */
        public Builder setCity(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          city_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string city = 2;</code>
         * @return This builder for chaining.
         */
        public Builder clearCity() {
          
          city_ = getDefaultInstance().getCity();
          onChanged();
          return this;
        }
        /**
         * <code>string city = 2;</code>
         * @param value The bytes for city to set.
         * @return This builder for chaining.
         */
        public Builder setCityBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          city_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object state_ = "";
        /**
         * <code>string state = 3;</code>
         * @return The state.
         */
        public java.lang.String getState() {
          java.lang.Object ref = state_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            state_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string state = 3;</code>
         * @return The bytes for state.
         */
        public com.google.protobuf.ByteString
            getStateBytes() {
          java.lang.Object ref = state_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            state_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string state = 3;</code>
         * @param value The state to set.
         * @return This builder for chaining.
         */
        public Builder setState(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          state_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string state = 3;</code>
         * @return This builder for chaining.
         */
        public Builder clearState() {
          
          state_ = getDefaultInstance().getState();
          onChanged();
          return this;
        }
        /**
         * <code>string state = 3;</code>
         * @param value The bytes for state to set.
         * @return This builder for chaining.
         */
        public Builder setStateBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          state_ = value;
          onChanged();
          return this;
        }

        private java.lang.Object zipCode_ = "";
        /**
         * <code>string zipCode = 4;</code>
         * @return The zipCode.
         */
        public java.lang.String getZipCode() {
          java.lang.Object ref = zipCode_;
          if (!(ref instanceof java.lang.String)) {
            com.google.protobuf.ByteString bs =
                (com.google.protobuf.ByteString) ref;
            java.lang.String s = bs.toStringUtf8();
            zipCode_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>string zipCode = 4;</code>
         * @return The bytes for zipCode.
         */
        public com.google.protobuf.ByteString
            getZipCodeBytes() {
          java.lang.Object ref = zipCode_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            zipCode_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>string zipCode = 4;</code>
         * @param value The zipCode to set.
         * @return This builder for chaining.
         */
        public Builder setZipCode(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  
          zipCode_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>string zipCode = 4;</code>
         * @return This builder for chaining.
         */
        public Builder clearZipCode() {
          
          zipCode_ = getDefaultInstance().getZipCode();
          onChanged();
          return this;
        }
        /**
         * <code>string zipCode = 4;</code>
         * @param value The bytes for zipCode to set.
         * @return This builder for chaining.
         */
        public Builder setZipCodeBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
          
          zipCode_ = value;
          onChanged();
          return this;
        }
        @java.lang.Override
        public final Builder setUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.setUnknownFields(unknownFields);
        }

        @java.lang.Override
        public final Builder mergeUnknownFields(
            final com.google.protobuf.UnknownFieldSet unknownFields) {
          return super.mergeUnknownFields(unknownFields);
        }


        // @@protoc_insertion_point(builder_scope:com.javatab.kafka.model.proto.User.Address)
      }

      // @@protoc_insertion_point(class_scope:com.javatab.kafka.model.proto.User.Address)
      private static final com.javatab.kafka.model.proto.UserProtos.User.Address DEFAULT_INSTANCE;
      static {
        DEFAULT_INSTANCE = new com.javatab.kafka.model.proto.UserProtos.User.Address();
      }

      public static com.javatab.kafka.model.proto.UserProtos.User.Address getDefaultInstance() {
        return DEFAULT_INSTANCE;
      }

      private static final com.google.protobuf.Parser<Address>
          PARSER = new com.google.protobuf.AbstractParser<Address>() {
        @java.lang.Override
        public Address parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new Address(input, extensionRegistry);
        }
      };

      public static com.google.protobuf.Parser<Address> parser() {
        return PARSER;
      }

      @java.lang.Override
      public com.google.protobuf.Parser<Address> getParserForType() {
        return PARSER;
      }

      @java.lang.Override
      public com.javatab.kafka.model.proto.UserProtos.User.Address getDefaultInstanceForType() {
        return DEFAULT_INSTANCE;
      }

    }

    public static final int NAME_FIELD_NUMBER = 1;
    private volatile java.lang.Object name_;
    /**
     * <code>string name = 1;</code>
     * @return The name.
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        name_ = s;
        return s;
      }
    }
    /**
     * <code>string name = 1;</code>
     * @return The bytes for name.
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int ID_FIELD_NUMBER = 2;
    private volatile java.lang.Object id_;
    /**
     * <code>string id = 2;</code>
     * @return The id.
     */
    public java.lang.String getId() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        id_ = s;
        return s;
      }
    }
    /**
     * <code>string id = 2;</code>
     * @return The bytes for id.
     */
    public com.google.protobuf.ByteString
        getIdBytes() {
      java.lang.Object ref = id_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        id_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int EMAIL_FIELD_NUMBER = 3;
    private volatile java.lang.Object email_;
    /**
     * <code>string email = 3;</code>
     * @return The email.
     */
    public java.lang.String getEmail() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        email_ = s;
        return s;
      }
    }
    /**
     * <code>string email = 3;</code>
     * @return The bytes for email.
     */
    public com.google.protobuf.ByteString
        getEmailBytes() {
      java.lang.Object ref = email_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        email_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int CREATED_ON_FIELD_NUMBER = 4;
    private com.google.protobuf.Timestamp createdOn_;
    /**
     * <code>.google.protobuf.Timestamp created_on = 4;</code>
     * @return Whether the createdOn field is set.
     */
    public boolean hasCreatedOn() {
      return createdOn_ != null;
    }
    /**
     * <code>.google.protobuf.Timestamp created_on = 4;</code>
     * @return The createdOn.
     */
    public com.google.protobuf.Timestamp getCreatedOn() {
      return createdOn_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdOn_;
    }
    /**
     * <code>.google.protobuf.Timestamp created_on = 4;</code>
     */
    public com.google.protobuf.TimestampOrBuilder getCreatedOnOrBuilder() {
      return getCreatedOn();
    }

    public static final int ADDRESS_FIELD_NUMBER = 5;
    private com.javatab.kafka.model.proto.UserProtos.User.Address address_;
    /**
     * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
     * @return Whether the address field is set.
     */
    public boolean hasAddress() {
      return address_ != null;
    }
    /**
     * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
     * @return The address.
     */
    public com.javatab.kafka.model.proto.UserProtos.User.Address getAddress() {
      return address_ == null ? com.javatab.kafka.model.proto.UserProtos.User.Address.getDefaultInstance() : address_;
    }
    /**
     * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
     */
    public com.javatab.kafka.model.proto.UserProtos.User.AddressOrBuilder getAddressOrBuilder() {
      return getAddress();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getNameBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, name_);
      }
      if (!getIdBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, email_);
      }
      if (createdOn_ != null) {
        output.writeMessage(4, getCreatedOn());
      }
      if (address_ != null) {
        output.writeMessage(5, getAddress());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getNameBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, name_);
      }
      if (!getIdBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(2, id_);
      }
      if (!getEmailBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, email_);
      }
      if (createdOn_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getCreatedOn());
      }
      if (address_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getAddress());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.javatab.kafka.model.proto.UserProtos.User)) {
        return super.equals(obj);
      }
      com.javatab.kafka.model.proto.UserProtos.User other = (com.javatab.kafka.model.proto.UserProtos.User) obj;

      if (!getName()
          .equals(other.getName())) return false;
      if (!getId()
          .equals(other.getId())) return false;
      if (!getEmail()
          .equals(other.getEmail())) return false;
      if (hasCreatedOn() != other.hasCreatedOn()) return false;
      if (hasCreatedOn()) {
        if (!getCreatedOn()
            .equals(other.getCreatedOn())) return false;
      }
      if (hasAddress() != other.hasAddress()) return false;
      if (hasAddress()) {
        if (!getAddress()
            .equals(other.getAddress())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + NAME_FIELD_NUMBER;
      hash = (53 * hash) + getName().hashCode();
      hash = (37 * hash) + ID_FIELD_NUMBER;
      hash = (53 * hash) + getId().hashCode();
      hash = (37 * hash) + EMAIL_FIELD_NUMBER;
      hash = (53 * hash) + getEmail().hashCode();
      if (hasCreatedOn()) {
        hash = (37 * hash) + CREATED_ON_FIELD_NUMBER;
        hash = (53 * hash) + getCreatedOn().hashCode();
      }
      if (hasAddress()) {
        hash = (37 * hash) + ADDRESS_FIELD_NUMBER;
        hash = (53 * hash) + getAddress().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.javatab.kafka.model.proto.UserProtos.User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.javatab.kafka.model.proto.UserProtos.User prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code com.javatab.kafka.model.proto.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:com.javatab.kafka.model.proto.User)
        com.javatab.kafka.model.proto.UserProtos.UserOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.javatab.kafka.model.proto.UserProtos.User.class, com.javatab.kafka.model.proto.UserProtos.User.Builder.class);
      }

      // Construct using com.javatab.kafka.model.proto.UserProtos.User.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        name_ = "";

        id_ = "";

        email_ = "";

        if (createdOnBuilder_ == null) {
          createdOn_ = null;
        } else {
          createdOn_ = null;
          createdOnBuilder_ = null;
        }
        if (addressBuilder_ == null) {
          address_ = null;
        } else {
          address_ = null;
          addressBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.javatab.kafka.model.proto.UserProtos.internal_static_com_javatab_kafka_model_proto_User_descriptor;
      }

      @java.lang.Override
      public com.javatab.kafka.model.proto.UserProtos.User getDefaultInstanceForType() {
        return com.javatab.kafka.model.proto.UserProtos.User.getDefaultInstance();
      }

      @java.lang.Override
      public com.javatab.kafka.model.proto.UserProtos.User build() {
        com.javatab.kafka.model.proto.UserProtos.User result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.javatab.kafka.model.proto.UserProtos.User buildPartial() {
        com.javatab.kafka.model.proto.UserProtos.User result = new com.javatab.kafka.model.proto.UserProtos.User(this);
        result.name_ = name_;
        result.id_ = id_;
        result.email_ = email_;
        if (createdOnBuilder_ == null) {
          result.createdOn_ = createdOn_;
        } else {
          result.createdOn_ = createdOnBuilder_.build();
        }
        if (addressBuilder_ == null) {
          result.address_ = address_;
        } else {
          result.address_ = addressBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.javatab.kafka.model.proto.UserProtos.User) {
          return mergeFrom((com.javatab.kafka.model.proto.UserProtos.User)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.javatab.kafka.model.proto.UserProtos.User other) {
        if (other == com.javatab.kafka.model.proto.UserProtos.User.getDefaultInstance()) return this;
        if (!other.getName().isEmpty()) {
          name_ = other.name_;
          onChanged();
        }
        if (!other.getId().isEmpty()) {
          id_ = other.id_;
          onChanged();
        }
        if (!other.getEmail().isEmpty()) {
          email_ = other.email_;
          onChanged();
        }
        if (other.hasCreatedOn()) {
          mergeCreatedOn(other.getCreatedOn());
        }
        if (other.hasAddress()) {
          mergeAddress(other.getAddress());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.javatab.kafka.model.proto.UserProtos.User parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.javatab.kafka.model.proto.UserProtos.User) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object name_ = "";
      /**
       * <code>string name = 1;</code>
       * @return The name.
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @return The bytes for name.
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string name = 1;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>string name = 1;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        name_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object id_ = "";
      /**
       * <code>string id = 2;</code>
       * @return The id.
       */
      public java.lang.String getId() {
        java.lang.Object ref = id_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          id_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @return The bytes for id.
       */
      public com.google.protobuf.ByteString
          getIdBytes() {
        java.lang.Object ref = id_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          id_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string id = 2;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        
        id_ = getDefaultInstance().getId();
        onChanged();
        return this;
      }
      /**
       * <code>string id = 2;</code>
       * @param value The bytes for id to set.
       * @return This builder for chaining.
       */
      public Builder setIdBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        id_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object email_ = "";
      /**
       * <code>string email = 3;</code>
       * @return The email.
       */
      public java.lang.String getEmail() {
        java.lang.Object ref = email_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          email_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @return The bytes for email.
       */
      public com.google.protobuf.ByteString
          getEmailBytes() {
        java.lang.Object ref = email_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          email_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string email = 3;</code>
       * @param value The email to set.
       * @return This builder for chaining.
       */
      public Builder setEmail(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        email_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmail() {
        
        email_ = getDefaultInstance().getEmail();
        onChanged();
        return this;
      }
      /**
       * <code>string email = 3;</code>
       * @param value The bytes for email to set.
       * @return This builder for chaining.
       */
      public Builder setEmailBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        email_ = value;
        onChanged();
        return this;
      }

      private com.google.protobuf.Timestamp createdOn_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> createdOnBuilder_;
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       * @return Whether the createdOn field is set.
       */
      public boolean hasCreatedOn() {
        return createdOnBuilder_ != null || createdOn_ != null;
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       * @return The createdOn.
       */
      public com.google.protobuf.Timestamp getCreatedOn() {
        if (createdOnBuilder_ == null) {
          return createdOn_ == null ? com.google.protobuf.Timestamp.getDefaultInstance() : createdOn_;
        } else {
          return createdOnBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       */
      public Builder setCreatedOn(com.google.protobuf.Timestamp value) {
        if (createdOnBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          createdOn_ = value;
          onChanged();
        } else {
          createdOnBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       */
      public Builder setCreatedOn(
          com.google.protobuf.Timestamp.Builder builderForValue) {
        if (createdOnBuilder_ == null) {
          createdOn_ = builderForValue.build();
          onChanged();
        } else {
          createdOnBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       */
      public Builder mergeCreatedOn(com.google.protobuf.Timestamp value) {
        if (createdOnBuilder_ == null) {
          if (createdOn_ != null) {
            createdOn_ =
              com.google.protobuf.Timestamp.newBuilder(createdOn_).mergeFrom(value).buildPartial();
          } else {
            createdOn_ = value;
          }
          onChanged();
        } else {
          createdOnBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       */
      public Builder clearCreatedOn() {
        if (createdOnBuilder_ == null) {
          createdOn_ = null;
          onChanged();
        } else {
          createdOn_ = null;
          createdOnBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       */
      public com.google.protobuf.Timestamp.Builder getCreatedOnBuilder() {
        
        onChanged();
        return getCreatedOnFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       */
      public com.google.protobuf.TimestampOrBuilder getCreatedOnOrBuilder() {
        if (createdOnBuilder_ != null) {
          return createdOnBuilder_.getMessageOrBuilder();
        } else {
          return createdOn_ == null ?
              com.google.protobuf.Timestamp.getDefaultInstance() : createdOn_;
        }
      }
      /**
       * <code>.google.protobuf.Timestamp created_on = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder> 
          getCreatedOnFieldBuilder() {
        if (createdOnBuilder_ == null) {
          createdOnBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Timestamp, com.google.protobuf.Timestamp.Builder, com.google.protobuf.TimestampOrBuilder>(
                  getCreatedOn(),
                  getParentForChildren(),
                  isClean());
          createdOn_ = null;
        }
        return createdOnBuilder_;
      }

      private com.javatab.kafka.model.proto.UserProtos.User.Address address_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.javatab.kafka.model.proto.UserProtos.User.Address, com.javatab.kafka.model.proto.UserProtos.User.Address.Builder, com.javatab.kafka.model.proto.UserProtos.User.AddressOrBuilder> addressBuilder_;
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       * @return Whether the address field is set.
       */
      public boolean hasAddress() {
        return addressBuilder_ != null || address_ != null;
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       * @return The address.
       */
      public com.javatab.kafka.model.proto.UserProtos.User.Address getAddress() {
        if (addressBuilder_ == null) {
          return address_ == null ? com.javatab.kafka.model.proto.UserProtos.User.Address.getDefaultInstance() : address_;
        } else {
          return addressBuilder_.getMessage();
        }
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       */
      public Builder setAddress(com.javatab.kafka.model.proto.UserProtos.User.Address value) {
        if (addressBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          address_ = value;
          onChanged();
        } else {
          addressBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       */
      public Builder setAddress(
          com.javatab.kafka.model.proto.UserProtos.User.Address.Builder builderForValue) {
        if (addressBuilder_ == null) {
          address_ = builderForValue.build();
          onChanged();
        } else {
          addressBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       */
      public Builder mergeAddress(com.javatab.kafka.model.proto.UserProtos.User.Address value) {
        if (addressBuilder_ == null) {
          if (address_ != null) {
            address_ =
              com.javatab.kafka.model.proto.UserProtos.User.Address.newBuilder(address_).mergeFrom(value).buildPartial();
          } else {
            address_ = value;
          }
          onChanged();
        } else {
          addressBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       */
      public Builder clearAddress() {
        if (addressBuilder_ == null) {
          address_ = null;
          onChanged();
        } else {
          address_ = null;
          addressBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       */
      public com.javatab.kafka.model.proto.UserProtos.User.Address.Builder getAddressBuilder() {
        
        onChanged();
        return getAddressFieldBuilder().getBuilder();
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       */
      public com.javatab.kafka.model.proto.UserProtos.User.AddressOrBuilder getAddressOrBuilder() {
        if (addressBuilder_ != null) {
          return addressBuilder_.getMessageOrBuilder();
        } else {
          return address_ == null ?
              com.javatab.kafka.model.proto.UserProtos.User.Address.getDefaultInstance() : address_;
        }
      }
      /**
       * <code>.com.javatab.kafka.model.proto.User.Address address = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.javatab.kafka.model.proto.UserProtos.User.Address, com.javatab.kafka.model.proto.UserProtos.User.Address.Builder, com.javatab.kafka.model.proto.UserProtos.User.AddressOrBuilder> 
          getAddressFieldBuilder() {
        if (addressBuilder_ == null) {
          addressBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.javatab.kafka.model.proto.UserProtos.User.Address, com.javatab.kafka.model.proto.UserProtos.User.Address.Builder, com.javatab.kafka.model.proto.UserProtos.User.AddressOrBuilder>(
                  getAddress(),
                  getParentForChildren(),
                  isClean());
          address_ = null;
        }
        return addressBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:com.javatab.kafka.model.proto.User)
    }

    // @@protoc_insertion_point(class_scope:com.javatab.kafka.model.proto.User)
    private static final com.javatab.kafka.model.proto.UserProtos.User DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.javatab.kafka.model.proto.UserProtos.User();
    }

    public static com.javatab.kafka.model.proto.UserProtos.User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<User>
        PARSER = new com.google.protobuf.AbstractParser<User>() {
      @java.lang.Override
      public User parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new User(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<User> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<User> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.javatab.kafka.model.proto.UserProtos.User getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_javatab_kafka_model_proto_User_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_javatab_kafka_model_proto_User_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_com_javatab_kafka_model_proto_User_Address_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_com_javatab_kafka_model_proto_User_Address_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nuser.proto\022\035com.javatab.kafka.model.pr" +
      "oto\032\037google/protobuf/timestamp.proto\"\352\001\n" +
      "\004User\022\014\n\004name\030\001 \001(\t\022\n\n\002id\030\002 \001(\t\022\r\n\005email" +
      "\030\003 \001(\t\022.\n\ncreated_on\030\004 \001(\0132\032.google.prot" +
      "obuf.Timestamp\022<\n\007address\030\005 \001(\0132+.com.ja" +
      "vatab.kafka.model.proto.User.Address\032K\n\007" +
      "Address\022\022\n\nstreetName\030\001 \001(\t\022\014\n\004city\030\002 \001(" +
      "\t\022\r\n\005state\030\003 \001(\t\022\017\n\007zipCode\030\004 \001(\tB\014B\nUse" +
      "rProtosb\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.TimestampProto.getDescriptor(),
        });
    internal_static_com_javatab_kafka_model_proto_User_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_com_javatab_kafka_model_proto_User_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_javatab_kafka_model_proto_User_descriptor,
        new java.lang.String[] { "Name", "Id", "Email", "CreatedOn", "Address", });
    internal_static_com_javatab_kafka_model_proto_User_Address_descriptor =
      internal_static_com_javatab_kafka_model_proto_User_descriptor.getNestedTypes().get(0);
    internal_static_com_javatab_kafka_model_proto_User_Address_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_com_javatab_kafka_model_proto_User_Address_descriptor,
        new java.lang.String[] { "StreetName", "City", "State", "ZipCode", });
    com.google.protobuf.TimestampProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
